### ISSUE TITLE
7zipa.exe missing in Windows if "Create archive" option is enabled

### ISSUE THREAD

**Issue by hjstrauss** [JackGruber/joplin-plugin-backup#67] opened 2024-02-02 10:23 UTC
Hi there,
At first I want to **thank you** for this very nice and handy plugin.
Unfortunately, there is an error in my case if I mark the option *Create archive* for the backups.
An error popup is shown like the one below:
![image](https://github.com/JackGruber/joplin-plugin-backup/assets/68334505/bc8eec9f-d45f-45fb-bf3b-34b86da4cf4e)
It indicates that *7zipa.exe* is being searched in a specific subdirectory and not being found there.
Normally, that would be no big problem because I have added this to the location including all necessary additional files.
But it seems as if an update of the plugin removes the subdirectories and the error pop's up again.
It would be nice if you could give a solution here.
Thank you very much,
Hans-Joerg

**Comment by JackGruber** [comment] 2024-02-02 16:30
Do you use the build in version of the plugin or the downloaded versuon.

When the build in version, which joplin version?

**Comment by personalizedrefrigerator** [comment] 2024-02-02 20:01
I just tested on Windows 11, Joplin 2.13.15, Simple Backup 1.3.6 and am not experiencing the issue.

If I then upgrade Joplin to version 2.14.11 and use the non-built-in Simple Backup plugin, I can reproduce this issue. Inspecting the `cache/io.github.jackgruber.backup` directory, I don't see an extracted copy of 7Zip.

Because it works in Joplin 2.13.15, I suspect that this is a bug in Joplin. (I'm looking into it).

**Comment by hjstrauss** [comment] 2024-02-03 11:41
Hi,
I use **Joplin 2.14.11 (prod, win32)** and **Simple Backup: 1.3.6** where thew backup has been installed manually. I feel it is the same as with @personalizedrefrigerator .
I removed the manual installation and then got the internal version and that works fine, thank you:-)
Kind regards,
Hans-Joerg

**Comment by personalizedrefrigerator** [comment] 2024-02-10 14:51
This should be fixed in Joplin 2.14.13.

**Comment by hjstrauss** [comment] 2024-02-11 11:45
Yes, it is fixed for me now as well. Thank you very much for all your support :-)

**Comment by hjstrauss** [comment] 2024-02-11 11:45
Closed as solved.

**Closed** 2024-02-19 15:01 UTC
